### ISSUE TITLE
Arithmetic operators don't handle well zero-length vectors

### ISSUE THREAD

**Issue by OfekShilon** [r-lib/bit64#10]
Example:
```
> a <- as.integer64(c(6,5)); a
integer64
[1] 6 5
> b <- as.integer64(); b
integer64(0)
> a*b
integer64
[1] 567545821093824 21474836490 
```

**Comment by truecluster** [comment]
Try to wrap up stuff before handing over maintenance to Michael Chirico, but cannot replicate.

**Comment by MichaelChirico** [comment]
Hmm I believe this is already fixed on `master`:

```r
as.integer64(1) * integer64()
# integer64(0)
```

**Comment by MichaelChirico** [comment]
Yes, this was incorporated in d60b6c5b45fed915a607aaca3784e0dde1b1dfbe.

I'll add some regression tests to close.
