### ISSUE TITLE
Rename master branch to main?

### ISSUE THREAD

**Issue by hadley** [r-lib/bit64#104]

**Comment by MichaelChirico** [comment]
Sure, I think you have a good workflow for making the transition if you want to make the change yourself? Otherwise I'll try and look up how to do so after the next release.

**Comment by hadley** [comment]
You can just call `usethis::git_default_branch_rename()`. It will break existing PRs though.

**Comment by MichaelChirico** [comment]
Hmm, now's a good time to do it -- queue is basically clear.

**Comment by MichaelChirico** [comment]
```
Error in `usethis::git_default_branch_rename()`:
✖ You don't seem to have admin permissions for the source repo "r-lib/bit64", which is required to rename the default branch.
Run `rlang::last_trace()` to see where the error occurred.
```

**Comment by hadley** [comment]
Done!

**Comment by hadley** [comment]
(I'm also happy to give you admin permission if you want them)

**Comment by hadley** [comment]
Done!

**Comment by MichaelChirico** [comment]
@hadley IIUC I need you to update the default branch that appears on codecov.io as well. Please and thanks!

**Comment by hadley** [comment]
Done!
