### ISSUE TITLE
integer64/double multiplication is not commutative

### ISSUE THREAD

**Issue by OfekShilon** [r-lib/bit64#12]
Example:
```r
i <- as.integer64(2)
d <- 3.5
i*d
#integer64
#[1] 7
d*i
#integer64
#[1] 6
```

**Comment by MichaelChirico** [comment]
Hi @truecluster, just came across this issue. Noticed @OfekShilon fixed it in a fork (nice!). Are you still maintaining the package, or perhaps looking for someone to take over maintenance?

**Comment by MichaelChirico** [comment]
@OfekShilon for here and #12, it seems the discrepancy is intentional, see `?"bit64-package"`:

![screenshot of paragraph "Arithmetic precision and coercion" from the "bit64-package" help page](https://github.com/truecluster/bit64/assets/7606389/0d1ce72a-db29-46c2-b0de-2272ce759b29)

**Comment by MichaelChirico** [comment]
(don't really understand why this behavior was chosen, but it is documented)
