### ISSUE TITLE
Double divided by integer64 gives wrong results

### ISSUE THREAD

**Issue by OfekShilon** [r-lib/bit64#14]
Example:
```r
d <- 2.5
i <- as.integer64(5)
d/i
#0.4
```
Should have been 0.5 - current implementation coerces `d` into `integer64` before the division.

**Comment by truecluster** [comment]
Try to wrap up stuff before handing over maintenance to Michael Chirico, but cannot replicate.

**Comment by MichaelChirico** [comment]
Continued in #92
