### ISSUE TITLE
bug in all.equal.integer64 for length(scale)>1

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/bit64#23]
Hi, I noticed you are using basically the same definition for `all.equal.integer64` as `base::all.equal.numeric()`; I just filed this bug & patch to base R:

https://bugs.r-project.org/show_bug.cgi?id=18272

Happy to file the same PR against `bit64`, but for now, waiting to see what r-devel wants to do about the bug.

**Comment by truecluster** [comment]
Hi Michael, you know best what to do here.
