### ISSUE TITLE
long vector support

### ISSUE THREAD

**Issue by ilia-kats** [r-lib/bit64#30]
It seems that bit64 does not support long vectors, I'm getting
```
Error in is.na.integer64(res) : 
  long vectors not supported yet: memory.c:3888
```
on R 4.3.0, bit64 4.0.5. As far as I can tell, fixing this requires replacing `LENGTH` calls with `XLENGTH` calls, but I'm not sure if this is the only change that's needed for full long vector compatibility.

**Comment by MichaelChirico** [comment]
Reproducible:

```r
x = integer64(.Machine$integer.max+1)
sum(is.na(x))
# Error in is.na.integer64(x) : 
#   long vectors not supported yet: memory.c:3940
```

**Comment by MichaelChirico** [comment]
Unfortunately the fix is not related to `LENGTH`/`XLENGTH`, here is the simple implementation of `is.na.integer64`:

https://github.com/r-lib/bit64/blob/4affcf549b68c06338e841def00a0f08efea3162/src/integer64.c#L904-L912

**Comment by MichaelChirico** [comment]
Fixed `is.na()`, certainly there are others needing to be addressed.

Committed directly to `master` by mistake: ac766a96da3058954e13391e46a6c56685922375
