### ISSUE TITLE
`is.nan.integer64()` and `is.infinite.integer64()` don't return TRUE for NaN and Inf values respectively 

### ISSUE THREAD

**Issue by Rosie23** [r-lib/bit64#36]
`is.nan.integer64 ` doesn't return TRUE for NaN values
`is.infinite.integer64 ` doesn't return TRUE for Inf values

```
  is.nan.integer64(NaN) # FALSE
  as.integer64(NaN) # NA
  is.nan.integer64(as.integer64(NaN)) # FALSE
  
  is.infinite.integer64(Inf) # FALSE
  as.integer64(Inf) # NA Warning message: In as.integer64.double(Inf) : NAs produced by integer64 overflow
  is.infinite.integer64(as.integer64(Inf)) # FALSE
```

**Comment by MichaelChirico** [comment]
`Inf` and `NaN` are not integer64 values, they are doubles.

Also, don't call `is.nan.integer64()` or `is.infinite.integer64()` directly -- rely on S3 dispatch to do so.

`is.infinite(NA_real_)` is `FALSE`, so `is.infinite(NA_integer64_)` should also be `FALSE`.

We _could_ add an error in `is.nan.integer64()` and `is.infinite.integer64()` if they are called with non-`integer64` input, but I'd rather just unexport them to make doing so very difficult (require `:::` access: #76.
