### ISSUE TITLE
Feature request: as.integer64.raw()

### ISSUE THREAD

**Issue by coolbutuseless** [r-lib/bit64#39]
It would be nice to have a method which converts a raw vector into an integer64.

This could be used (for example) when interacting with data from connections via `readBin()` et al

For example to read 2 regular R integers from a connection

``` r
two_ints <- readBin(conn, size = 4, n = 2)
```

For `integer64` types, these could be read using a two step process using this new `as.integer64.raw()`

``` r
raw_vec <- readBin(conn, size = 2 * 8, n = 2)
two_int64s <- as.integer64.raw(raw_vec)
```

Possible implementation issue:

* This deviates from what be expected in comparison to the other `as.integer64` methods i.e. instead of 1 integer64 for each input, there would be 1 integer64 for each cluster of 8 input values.

Is there any interest in developing such a feature?  Would a PR on this issue be considered?

**Comment by MichaelChirico** [comment]
I'm not sure I quite understand, could you add a more concrete example? I'm not as fluent with readBin().

WDYT about a direct readInt64() equivalent instead, would that be enough?

the idea for as.integer64.raw(x) would be like

```r
dim(x)=c(4, length(x)/4)
# each column is now an integer64 value
```

is that right? that would make length(as.integer64(x)) == length(x)/4 which strikes me as strange & incongruent with other coercion methods...

**Comment by coolbutuseless** [comment]
I'm currently parsing binary data from a file.  Many numeric types in R are supported directly by `readBin()`

The known format of the binary data file is a sequence of records of the form:

```
[int32][double][double][int64]
[int32][double][double][int64]
...
```

My current code for parsing looks something like this:

``` r
# open a binary connection to the file to read from it
conn <- open(conn, 'rb') 

# Read the next 4 bytes as a signed integer
my_int <- readBin(conn, 'integer', size = 4, n = 1) 

# Read the next 16 bytes as 2 double precision floating points
my_dbls <- readBin(conn, 'double', size = 8, n = 2)

# Read the next 8 bytes.  Want to interpret this as an 'integer64' eventually.
# For now just read in 8 raw bytes
my_sizet_raw <- readBin(conn, 'raw', size = 1, n = 8)

# Convert these 8 raw bytes to an 'integer64'
my_sizet <- bit64::as.integer64.raw(my_sizet_raw)
```


A direct `readInt64()` would also be useful, but maybe not as general purpose(?)

he advantage of `as.integer64.raw` is that it wouldn't have to concern itself with R connection objects. Also users might be sourcing their raw bytes from other places.

**Comment by coolbutuseless** [comment]
I ended up writing a snippet of code. Not exactly sure if it's correct.

``` r
SEXP as_integer64_(SEXP raw_vec_) {
  
  int nprotect = 0;
  int input_len = length(raw_vec_);
  
  if (input_len % 8 != 0 || TYPEOF(raw_vec_) != RAWSXP) {
    error("Input must be a raw vector with length a multiple of 8");
  }
  
  int N = input_len / 8;
  SEXP res_ = PROTECT(allocVector(REALSXP, N)); nprotect++;
  
  memcpy(REAL(res_), RAW(raw_vec_), input_len);
  
  setAttrib(res_, R_ClassSymbol, PROTECT(mkString("integer64"))); nprotect++;
  
  UNPROTECT(nprotect);
  return res_;
}
```

```
> vec <- as.raw(1:16)
> .Call(as_integer64_, vec)
integer64
[1] 578437695752307201  1157159078456920585
```

**Comment by MichaelChirico** [comment]
I definitely think yours is a good use case to support, however I don't think `as.integer64` is an appropriate place for it since the output will not have the same length. Basically I would expect `as.integer64.raw(x)` to be identical to `as.integer64(as.integer(x))`.

I'm not sure if it's possible to get `writeBin()`/`readBin()` to help here but I can hack them:

```r
x = as.integer64(1:10)
tmp <- tempfile()

writeBin(unclass(x), tmp)

y = readBin(tmp, double(), length(x)) # or integer64() apparently
class(y) = 'integer64'

identical(x, y)
# [1] TRUE
```

What do you think would be a good API here?

**Comment by coolbutuseless** [comment]
Ahhh! that's so much easier than what I was doing!

I will close this issue as using `readBin()` + adding a class of `integer64` is sufficient and I don't have any need now for a custom function within this package.

Thanks for your insight!

**Comment by newbluejeans** [comment]
Thank you for the great workaround. I use bit64 on Windows 11 64-bit, R version 4.6. Functions as.raw(integer64) and as.integer64(raw) do not seem to work. Using your suggestion, I formulated the following vectorized simple wrapper functions, which seem to work well.

# Function for converting a vector of Integer64 values to a list of raw values:
int64ToRaw <- function(object, endian = "little"){
	lapply(object, function(X)
		writeBin(object = unclass(bit64::as.integer64(X)),
			con = raw(), size = 8L, endian = endian, useBytes = FALSE))
}

# Function for converting a list of raw values to a vector of Integer64 values:
rawToInt64 <- function(object, endian = "little"){
	X <- bit64::integer64(0)
	for (el in object){
		X <- c(X, `class<-`(readBin(con = el, what = bit64::integer64(0),
			n = 1L, size = 8L, signed = TRUE, endian = endian), "integer64"))
	}
	return(X)
}
